name: jana_aastha
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter_screenutil: ^5.5.4
  http: ^0.13.5
  cached_network_image: ^3.2.0
  flutter_html: ^2.2.1
  nepali_utils: ^3.0.3
  intl: ^0.17.0
  connectivity_plus: ^2.3.7





  
  flutter:  
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/
   
   

